[program:profiles_api]
command = /usr/local/apps/profiles-rest-api/env/bin/gunicorn project.wsgi:application --bind unix:/tmp/gunicorn.sock
directory = /usr/local/apps/profiles-rest-api/project/
user = root
autostart = true
autorestart = true
stdout_logfile = /var/log/supervisor/profiles_api.log
stderr_logfile = /var/log/supervisor/profiles_api_err.log
