[program:profiles_api]
command = /usr/local/apps/profiles-rest-api/env/bin/gunicorn profiles_api.wsgi:application --bind 127.0.0.1:8000
directory = /usr/local/apps/profiles-rest-api/
user = root
autostart = true
autorestart = true
stdout_logfile = /var/log/supervisor/profiles_api.log
stderr_logfile = /var/log/supervisor/profiles_api_err.log
