# Generated by Django 2.2 on 2026-06-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20260622_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
