# Generated by Django 2.2 on 2026-06-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20260622_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
